Fixes

diff --git a/install.yaml b/install.yaml
--- a/install.yaml
+++ b/install.yaml
@@ -7,51 +7,26 @@ name: addon-template
 # or doing a sanity check for requirements.
 # DDEV environment variables can be interpolated into these actions
 pre_install_actions:
-  # Actions with #ddev-nodisplay will not show the execution of the action, but may show their output
-# - |
-  # #ddev-nodisplay
+- |
+  #ddev-nodisplay
   #ddev-description:Check architecture type for incompatible arm64 type
-  # if [ "$(arch)" = "arm64" -o "$(arch)" = "aarch64" ]; then
-    # echo "This package does not work on arm64 machines";
-    # exit 1;
-  #fi
-
-# - "docker volume rm ddev-${DDEV_PROJECT}_solr 2>/dev/null || true"
-#- |
-#  # Using #ddev-nodisplay tells ddev to be quiet about this action and not show it or its output.
-#  #ddev-nodisplay
-#  #ddev-description:Remove solr volume
-#  if ! ( ddev debug capabilities 2>/dev/null | grep multiple-dockerfiles >/dev/null 2>&1 ) ; then
-#    echo "This add-on requires DDEV v1.19.4 or higher, please upgrade." && exit 2
-#  fi
-#- 'echo "what is your platform.sh token" && read x'
-
-# This item shows templating using DDEV environment variables.
-# -
-#   #ddev-description:Touch a file to create it
-#   touch somefile.${DDEV_PROJECT_TYPE}.${DDEV_DOCROOT}.txt
-#
-
-# This item shows complex go templating possibilities based on yaml_read_files
-#- |
-#- #ddev-description:Create a config.platformsh.yaml
-#  cat <<EOF >.ddev/config.platformsh.yaml
-#  php_version: {{ trimPrefix "php:" .platformapp.type }}
-#  database:
-#    type: {{ regexReplaceAll ":.*$" .services.db.type "" }}
-#    version: {{ regexReplaceAll "^.*:" .services.db.type "" }}
-#
-#  docroot: {{ dig "web" "locations" "/" "root" "notfound" .platformapp }}
-#  {{ if eq .platformapp.build.flavor "composer" }}
-#  hooks:
-#    post-start:
-#      - composer: install
-#  {{ if .platformapp.hooks.deploy }}
-#      - exec: "{{ trimAll "\n" .platformapp.hooks.deploy | splitList "\n" | join ` && ` }}"
-#  {{ end }}
-#  {{ end }}
-#
-#  EOF
+  if [ "$(arch)" = "arm64" -o "$(arch)" = "aarch64" ]; then
+    echo "This package does not work on arm64 machines";
+    exit 1;
+  fi
+- |
+  # If there was an existing .ddev/web-build/Dockerfile.db2 we need to remove it
+  #ddev-nodisplay
+  #ddev-description:Check for existing Dockerfile.db2
+  if [ -f .ddev/web-build/Dockerfile.db2 ]; then
+    if grep "#ddev-generated" .ddev/web-build/Dockerfile.db2; then
+      echo "Removing Dockerfile.db2 from previous version of this add-on"
+      rm .ddev/web-build/Dockerfile.db2
+    else 
+      echo "Dockerfile.db2 needs to be removed but has been modified by the user. Please check it and remove it"
+      exit 2;
+    fi
+  fi
 
 # list of files and directories listed that are copied into project .ddev directory
 # Each file should contain #ddev-generated so it can be replaced by a later `ddev get`
@@ -68,18 +43,26 @@ global_files:
 
 # DDEV environment variables can be interpolated into these actions
 post_install_actions:
-# - chmod +x ~/.ddev/commands/web/somecommand
-# - touch somefile.${GOOS}.${DDEV_WEBSERVER}
-# - perl -pi -e 's/oldstring/newstring/g' docker-compose.addon-template.yaml
-
-# Shell actions that can be done during removal of the add-on
-removal_actions:
-# - rm ~/.ddev/commands/web/somecommand
+- |
+  #ddev-nodisplay
+  if [ -f .ddev/.env ] && ! grep '#ddev-generated' .ddev/.env; then
+    echo "Existing .ddev/.env does not have #ddev-generated, so it can't be updated"
+    exit 2
+  fi
+- |
+  #ddev-nodisplay
+  cat <<-END > .env
+  #ddev-generated
+  DB2_INSTANCE=db2inst1
+  DB2_EXTERNAL_PORT=50000
+  DB2_USER=db
+  DB2_PASSWORD=db
+  DB2_DATABASE=db
+  DB2_HOST=db2
+  END
 
 # Advanced usage - yaml files can be read in and then used as go template actions
 # in pre_install_actions and post_install_actions
 # See example in
 # https://github.com/rfay/ddev/blob/20220606_yaml_read_experiment/cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/install.yaml
 yaml_read_files:
-# someyaml: someyaml.yaml
-# otheryaml: someotheryaml.yaml
